"""
Ingredient configuration.

This module contains ingredients organized by categories.
"""

# Common ingredient categories and examples
INGREDIENT_CATEGORIES = [
    {
        "name": "Proteins",
        "ingredients": [
            {"id": "chicken", "name": "Chicken"},
            {"id": "beef", "name": "Beef"},
            {"id": "pork", "name": "Pork"},
            {"id": "lamb", "name": "Lamb"},
            {"id": "fish", "name": "Fish"},
            {"id": "salmon", "name": "Salmon"},
            {"id": "tuna", "name": "Tuna"},
            {"id": "shrimp", "name": "Shrimp"},
            {"id": "tofu", "name": "Tofu"},
            {"id": "tempeh", "name": "Tempeh"},
            {"id": "eggs", "name": "Eggs"},
            {"id": "beans", "name": "Beans"},
            {"id": "lentils", "name": "Lentils"},
            {"id": "chickpeas", "name": "Chickpeas"},
            {"id": "black_beans", "name": "Black Beans"},
            {"id": "kidney_beans", "name": "Kidney Beans"},
            {"id": "nuts", "name": "Nuts"},
            {"id": "almonds", "name": "Almonds"},
            {"id": "walnuts", "name": "Walnuts"},
            {"id": "cashews", "name": "Cashews"},
            {"id": "quinoa", "name": "Quinoa"},
            {"id": "turkey", "name": "Turkey"},
            {"id": "duck", "name": "Duck"},
            {"id": "crab", "name": "Crab"},
            {"id": "lobster", "name": "Lobster"},
            {"id": "scallops", "name": "Scallops"},
            {"id": "seitan", "name": "Seitan"},
        ]
    },
    {
        "name": "Vegetables",
        "ingredients": [
            {"id": "onion", "name": "Onion"},
            {"id": "red_onion", "name": "Red Onion"},
            {"id": "green_onion", "name": "Green Onion"},
            {"id": "garlic", "name": "Garlic"},
            {"id": "ginger", "name": "Ginger"},
            {"id": "tomato", "name": "Tomato"},
            {"id": "cherry_tomato", "name": "Cherry Tomato"},
            {"id": "potato", "name": "Potato"},
            {"id": "sweet_potato", "name": "Sweet Potato"},
            {"id": "carrot", "name": "Carrot"},
            {"id": "bell_pepper", "name": "Bell Pepper"},
            {"id": "hot_pepper", "name": "Hot Pepper"},
            {"id": "jalapeno", "name": "Jalapeño"},
            {"id": "lettuce", "name": "Lettuce"},
            {"id": "kale", "name": "Kale"},
            {"id": "spinach", "name": "Spinach"},
            {"id": "arugula", "name": "Arugula"},
            {"id": "broccoli", "name": "Broccoli"},
            {"id": "brussels_sprouts", "name": "Brussels Sprouts"},
            {"id": "zucchini", "name": "Zucchini"},
            {"id": "eggplant", "name": "Eggplant"},
            {"id": "mushroom", "name": "Mushroom"},
            {"id": "shiitake", "name": "Shiitake Mushroom"},
            {"id": "portobello", "name": "Portobello Mushroom"},
            {"id": "cucumber", "name": "Cucumber"},
            {"id": "corn", "name": "Corn"},
            {"id": "peas", "name": "Peas"},
            {"id": "cauliflower", "name": "Cauliflower"},
            {"id": "asparagus", "name": "Asparagus"},
            {"id": "celery", "name": "Celery"},
            {"id": "cabbage", "name": "Cabbage"},
            {"id": "beets", "name": "Beets"},
            {"id": "radishes", "name": "Radishes"},
            {"id": "artichoke", "name": "Artichoke"},
            {"id": "leek", "name": "Leek"},
            {"id": "bok_choy", "name": "Bok Choy"},
            {"id": "squash", "name": "Squash"},
            {"id": "pumpkin", "name": "Pumpkin"},
        ]
    },
    {
        "name": "Fruits",
        "ingredients": [
            {"id": "apple", "name": "Apple"},
            {"id": "banana", "name": "Banana"},
            {"id": "orange", "name": "Orange"},
            {"id": "grapefruit", "name": "Grapefruit"},
            {"id": "lemon", "name": "Lemon"},
            {"id": "lime", "name": "Lime"},
            {"id": "berries", "name": "Berries"},
            {"id": "strawberry", "name": "Strawberry"},
            {"id": "blueberry", "name": "Blueberry"},
            {"id": "raspberry", "name": "Raspberry"},
            {"id": "blackberry", "name": "Blackberry"},
            {"id": "pineapple", "name": "Pineapple"},
            {"id": "mango", "name": "Mango"},
            {"id": "peach", "name": "Peach"},
            {"id": "nectarine", "name": "Nectarine"},
            {"id": "plum", "name": "Plum"},
            {"id": "apricot", "name": "Apricot"},
            {"id": "cherry", "name": "Cherry"},
            {"id": "watermelon", "name": "Watermelon"},
            {"id": "cantaloupe", "name": "Cantaloupe"},
            {"id": "honeydew", "name": "Honeydew"},
            {"id": "grapes", "name": "Grapes"},
            {"id": "kiwi", "name": "Kiwi"},
            {"id": "avocado", "name": "Avocado"},
            {"id": "coconut", "name": "Coconut"},
            {"id": "pomegranate", "name": "Pomegranate"},
            {"id": "fig", "name": "Fig"},
            {"id": "dates", "name": "Dates"},
            {"id": "passion_fruit", "name": "Passion Fruit"},
            {"id": "dragonfruit", "name": "Dragon Fruit"},
            {"id": "guava", "name": "Guava"},
            {"id": "papaya", "name": "Papaya"},
        ]
    },
    {
        "name": "Dairy & Alternatives",
        "ingredients": [
            {"id": "milk", "name": "Milk"},
            {"id": "almond_milk", "name": "Almond Milk"},
            {"id": "soy_milk", "name": "Soy Milk"},
            {"id": "oat_milk", "name": "Oat Milk"},
            {"id": "coconut_milk", "name": "Coconut Milk"},
            {"id": "cheese", "name": "Cheese"},
            {"id": "cheddar", "name": "Cheddar Cheese"},
            {"id": "mozzarella", "name": "Mozzarella"},
            {"id": "parmesan", "name": "Parmesan"},
            {"id": "feta", "name": "Feta Cheese"},
            {"id": "goat_cheese", "name": "Goat Cheese"},
            {"id": "blue_cheese", "name": "Blue Cheese"},
            {"id": "butter", "name": "Butter"},
            {"id": "margarine", "name": "Margarine"},
            {"id": "yogurt", "name": "Yogurt"},
            {"id": "greek_yogurt", "name": "Greek Yogurt"},
            {"id": "cream", "name": "Cream"},
            {"id": "sour_cream", "name": "Sour Cream"},
            {"id": "cream_cheese", "name": "Cream Cheese"},
            {"id": "cottage_cheese", "name": "Cottage Cheese"},
            {"id": "ricotta", "name": "Ricotta"},
        ]
    },
    {
        "name": "Grains & Starches",
        "ingredients": [
            {"id": "rice", "name": "Rice"},
            {"id": "brown_rice", "name": "Brown Rice"},
            {"id": "basmati_rice", "name": "Basmati Rice"},
            {"id": "jasmine_rice", "name": "Jasmine Rice"},
            {"id": "pasta", "name": "Pasta"},
            {"id": "noodles", "name": "Noodles"},
            {"id": "rice_noodles", "name": "Rice Noodles"},
            {"id": "bread", "name": "Bread"},
            {"id": "whole_wheat_bread", "name": "Whole Wheat Bread"},
            {"id": "pita", "name": "Pita Bread"},
            {"id": "tortilla", "name": "Tortilla"},
            {"id": "oats", "name": "Oats"},
            {"id": "barley", "name": "Barley"},
            {"id": "couscous", "name": "Couscous"},
            {"id": "bulgur", "name": "Bulgur"},
            {"id": "cornmeal", "name": "Cornmeal"},
            {"id": "flour", "name": "Flour"},
            {"id": "whole_wheat_flour", "name": "Whole Wheat Flour"},
            {"id": "cornstarch", "name": "Cornstarch"},
        ]
    },
    {
        "name": "Herbs & Spices",
        "ingredients": [
            {"id": "salt", "name": "Salt"},
            {"id": "pepper", "name": "Pepper"},
            {"id": "cumin", "name": "Cumin"},
            {"id": "coriander", "name": "Coriander"},
            {"id": "paprika", "name": "Paprika"},
            {"id": "smoked_paprika", "name": "Smoked Paprika"},
            {"id": "cinnamon", "name": "Cinnamon"},
            {"id": "nutmeg", "name": "Nutmeg"},
            {"id": "oregano", "name": "Oregano"},
            {"id": "basil", "name": "Basil"},
            {"id": "thyme", "name": "Thyme"},
            {"id": "rosemary", "name": "Rosemary"},
            {"id": "sage", "name": "Sage"},
            {"id": "parsley", "name": "Parsley"},
            {"id": "cilantro", "name": "Cilantro"},
            {"id": "dill", "name": "Dill"},
            {"id": "mint", "name": "Mint"},
            {"id": "chili", "name": "Chili Powder"},
            {"id": "cayenne", "name": "Cayenne Pepper"},
            {"id": "turmeric", "name": "Turmeric"},
            {"id": "curry_powder", "name": "Curry Powder"},
            {"id": "garam_masala", "name": "Garam Masala"},
            {"id": "bay_leaf", "name": "Bay Leaf"},
            {"id": "vanilla", "name": "Vanilla"},
        ]
    },
    {
        "name": "Oils & Vinegars",
        "ingredients": [
            {"id": "olive_oil", "name": "Olive Oil"},
            {"id": "vegetable_oil", "name": "Vegetable Oil"},
            {"id": "coconut_oil", "name": "Coconut Oil"},
            {"id": "sesame_oil", "name": "Sesame Oil"},
            {"id": "vinegar", "name": "Vinegar"},
            {"id": "balsamic_vinegar", "name": "Balsamic Vinegar"},
            {"id": "apple_cider_vinegar", "name": "Apple Cider Vinegar"},
            {"id": "rice_vinegar", "name": "Rice Vinegar"},
            {"id": "red_wine_vinegar", "name": "Red Wine Vinegar"},
        ]
    },
    {
        "name": "Condiments & Sauces",
        "ingredients": [
            {"id": "ketchup", "name": "Ketchup"},
            {"id": "mustard", "name": "Mustard"},
            {"id": "mayonnaise", "name": "Mayonnaise"},
            {"id": "soy_sauce", "name": "Soy Sauce"},
            {"id": "hot_sauce", "name": "Hot Sauce"},
            {"id": "sriracha", "name": "Sriracha"},
            {"id": "worcestershire", "name": "Worcestershire Sauce"},
            {"id": "fish_sauce", "name": "Fish Sauce"},
            {"id": "bbq_sauce", "name": "BBQ Sauce"},
            {"id": "salsa", "name": "Salsa"},
            {"id": "pesto", "name": "Pesto"},
            {"id": "teriyaki", "name": "Teriyaki Sauce"},
            {"id": "tahini", "name": "Tahini"},
            {"id": "honey", "name": "Honey"},
            {"id": "maple_syrup", "name": "Maple Syrup"},
        ]
    },
    {
        "name": "Dessert Ingredients",
        "ingredients": [
            {"id": "sugar", "name": "Sugar"},
            {"id": "brown_sugar", "name": "Brown Sugar"},
            {"id": "powdered_sugar", "name": "Powdered Sugar"},
            {"id": "chocolate", "name": "Chocolate"},
            {"id": "chocolate_chips", "name": "Chocolate Chips"},
            {"id": "cocoa_powder", "name": "Cocoa Powder"},
            {"id": "baking_powder", "name": "Baking Powder"},
            {"id": "baking_soda", "name": "Baking Soda"},
            {"id": "vanilla_extract", "name": "Vanilla Extract"},
            {"id": "almond_extract", "name": "Almond Extract"},
            {"id": "caramel", "name": "Caramel"},
            {"id": "marshmallows", "name": "Marshmallows"},
            {"id": "graham_crackers", "name": "Graham Crackers"},
            {"id": "pie_crust", "name": "Pie Crust"},
            {"id": "ice_cream", "name": "Ice Cream"},
            {"id": "gelatin", "name": "Gelatin"},
            {"id": "pudding_mix", "name": "Pudding Mix"},
            {"id": "sprinkles", "name": "Sprinkles"},
            {"id": "cake_mix", "name": "Cake Mix"},
            {"id": "frosting", "name": "Frosting"},
        ]
    },
    {
        "name": "Beverage Ingredients",
        "ingredients": [
            {"id": "coffee", "name": "Coffee"},
            {"id": "tea", "name": "Tea"},
            {"id": "green_tea", "name": "Green Tea"},
            {"id": "black_tea", "name": "Black Tea"},
            {"id": "herbal_tea", "name": "Herbal Tea"},
            {"id": "fruit_juice", "name": "Fruit Juice"},
            {"id": "orange_juice", "name": "Orange Juice"},
            {"id": "apple_juice", "name": "Apple Juice"},
            {"id": "lemonade", "name": "Lemonade"},
            {"id": "soda", "name": "Soda"},
            {"id": "tonic_water", "name": "Tonic Water"},
            {"id": "sparkling_water", "name": "Sparkling Water"},
            {"id": "coconut_water", "name": "Coconut Water"},
            {"id": "protein_powder", "name": "Protein Powder"},
            {"id": "cocoa", "name": "Cocoa"},
            {"id": "hot_chocolate", "name": "Hot Chocolate"},
            {"id": "smoothie_ingredients", "name": "Smoothie Ingredients"},
        ]
    },
]

def get_all_ingredients():
    """Get a flat list of all ingredients from all categories."""
    return [ingredient for category in INGREDIENT_CATEGORIES for ingredient in category["ingredients"]]
